name: CI Module Test

on:
  workflow_call:
    inputs:
      module-path:
        required: true
        type: string
      repo:
        required: true
        type: string

jobs:
  test-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout module
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          path: ${{ inputs.module-path }}

      - name: Checkout openimis-fe_js
        uses: actions/checkout@v4
        with:
          repository: Y-Note-SAS/openimis-fe_js
          ref: feature-34644-fix
          path: openimis-fe_js
      - name: List files
        run: |
          echo "Contenu du workspace :"
          ls -R $GITHUB_WORKSPACE

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set MODULE_PATH env
        run: echo "MODULE_PATH=${GITHUB_WORKSPACE}/${{ inputs.module-path }}" >> $GITHUB_ENV

      - name: Generate openimis.json
        run: node $GITHUB_WORKSPACE/openimis-fe_js/generate-openimis.json.js

      - name: Install dependencies
        run: |
          MODULE_NAME=$(basename ${{ inputs.module-path }} | sed 's/^openimis-fe-//; s/_js$//')
          cd $GITHUB_WORKSPACE/openimis-fe_js
          echo "Contenu du package.json :"
          yarn load-config
          cat package.json
          yarn install
          cd $GITHUB_WORKSPACE/${{ inputs.module-path }}
          yarn link
          cd $GITHUB_WORKSPACE/openimis-fe_js
          yarn link @openimis/$MODULE_NAME

      - name: Run Jest tests for module
        run: |
          MODULE_NAME=$(basename ${{ inputs.module-path }} | sed 's/^openimis-//; s/_js$//')
          echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
          cd $GITHUB_WORKSPACE/openimis-fe_js
          echo "Contenu des tests :"
          ls -R $GITHUB_WORKSPACE/openimis-fe_js/node_modules/@openimis/$MODULE_NAME/tests
          yarn jest --config $GITHUB_WORKSPACE/openimis-fe_js/jest.config.js $GITHUB_WORKSPACE/openimis-fe_js/node_modules/@openimis/$MODULE_NAME/tests