name: CI Module Test

on:
  workflow_call:
    inputs:
      module-path:
        required: true
        type: string
      repo:
        required: true
        type: string

jobs:
  test-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout module
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          path: ${{ inputs.module-path }}

      - name: Checkout openimis-fe_js
        uses: actions/checkout@v4
        with:
          repository: Y-Note-SAS/openimis-fe_js
          ref: feature-34644-fix
          path: openimis-fe_js

      - name: Compute MODULE_NAME
        run: |
          MODULE_NAME=$(basename "${{ inputs.module-path }}" | sed 's/^openimis-fe-//; s/_js$//')
          MODULE_PATH=${GITHUB_WORKSPACE}/${{ inputs.module-path }}
          echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
          echo "MODULE_PATH=$MODULE_PATH" >> $GITHUB_ENV

      - name: List files
        run: |
          echo "Contenu du workspace :"
          ls -R $GITHUB_WORKSPACE

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate openimis.json
        run: node $GITHUB_WORKSPACE/openimis-fe_js/generate-openimis.json.js

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/openimis-fe_js
          echo "Contenu du package.json :"
          yarn load-config
          cat package.json
          yarn install
          cd $MODULE_PATH
          yarn link
          cp -v tests/* $GITHUB_WORKSPACE/openimis-fe_js/tests/
          rsync -v --exclude='index.js' ./src/ "$GITHUB_WORKSPACE/openimis-fe_js/src/"
          ls -R $GITHUB_WORKSPACE/openimis-fe_js/src/
          cd $GITHUB_WORKSPACE/openimis-fe_js
          yarn link @openimis/$MODULE_NAME

      - name: Run Jest tests for module
        run: |
          cd $GITHUB_WORKSPACE/openimis-fe_js
          echo "Contenu des tests :"
          ls -R $GITHUB_WORKSPACE/openimis-fe_js/tests
          yarn jest --coverage